### ISSUE TITLE
Prepare repo for Google bot

### ISSUE THREAD

**Issue by jennybc** [ropenscilabs/gauth#1]
@craigcitro I did not fill in the year or copyright holder in LICENSE. What should be there? You have write access here so you can tell me what to do or do it yourself.

I'm not expecting any action on this over the holidays!! Just thought I'd do it since the related convo keeps going over on bigquery. If you want to tell someone to watch this space or contribute in this space, now at least it exists.

**Comment by craigcitro** [comment]
Fixed up the last bits in 8f36ea6 and 191da3a, so we should be good to go. (Forgot about the issue or I'd have been fancy and added a note in the commit.)
